#!/usr/bin/tcsh

grep -v '^#' env.settings | awk -F'\n' 'length { print $1 }' | awk -F' ' '{ print "setenv " $1 " " $2 }' > .source-tcsh.gen
source .source-tcsh.gen

setenv PROJECT_MODULES 
set lspw=`(cd ..;echo $PWD)`
foreach dir (`(cd ..;\ls)`)
	setenv PROJECT_MODULES "$PROJECT_MODULES $lspw/$dir"
end
#setenv PROJECT_MODULES "$PROJECT_MODULES `echo $PWD`"
