#!/bin/bash
while IFS='
' read line
do
	if [[ ! $line == \#* ]] && [[ ! ${#line} == 0 ]] ; then
		VAR_NAME=`echo $line | awk -F " " '{print $1}'`
		VAR_VAL=`echo $line | awk -F " " '{print $2}'`
		export ${VAR_NAME}="${VAR_VAL}"
	fi
done < env.settings

PROJECT_MODULES=
for mod in `ls modules`
do
	PROJECT_MODULES+=" `pwd`/modules/$mod"
done
PROJECT_MODULES+=" `pwd`"
