#!/bin/bash

##
## Deploy applications.
## call with
##   - $1 being the name of the module to prepare files for
##   - $2 being the settings file name
##
## requires PROJECT_APPS_DIR set to a an existing folder for deployment
##

target_dir=$2/../../../../target

if [ -z "$PROJECT_APPS_DIR" ]; then
	echo "------> no application deployment directory set"
else
	if [ -d "$target_dir/application" ] ; then
		if [ -d "$PROJECT_APPS_DIR" ]; then
			for tarfile in `ls $target_dir/application|grep tar`
			do
				(cd $PROJECT_APPS_DIR; rm -fr $skb_module_appdir_name)
				(cd $PROJECT_APPS_DIR; mkdir $skb_module_appdir_name)
				cp $target_dir/application/$tarfile $PROJECT_APPS_DIR/$skb_module_appdir_name
				(cd $PROJECT_APPS_DIR/$skb_module_appdir_name; tar xvfz $tarfile)
				(cd $PROJECT_APPS_DIR/$skb_module_appdir_name; rm $tarfile)
				(cd $PROJECT_APPS_DIR/$skb_module_appdir_name/bin; init.sh)
			done
		else
			echo "------> deployment directory does not exist: ${PROJECT_APPS_DIR}"
		fi
	else
		echo "------> no folder for application found"
	fi
fi
